export const PROFILE_FAILED = 'PROFILE_LOADING';
export const ADD_PROFILE = 'ADD_PROFILE';
export const ADD_INSTITUTIONS = 'ADD_INSTITUTIONS';
export const ADD_STUDENTSTEAMEDWITH = 'ADD_STUDENTSTEAMEDWITH';
export const ADD_TASKSNOTSTARTED = 'ADD_TASKSNOTSTARTED';


export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
